export const SET_PROVIDER = "SET_PROVIDER";

export const SET_META_MASK_ADDRESS = "SET_META_MASK_ADDRESS";
export const DELETE_META_MASK_ADDRESS = "DELETE_META_MASK_ADDRESS";
export const SET_CONTRACT = "SET_CONTRACT";
export const DELETE_CONTRACT = "DELETE_CONTRACT";

export const SET_APPROVAL_FOR_LP = "SET_APPROVAL_FOR_LP";
export const SET_APPROVAL_FOR_ALIA = "SET_APPROVAL_FOR_ALIA";
export const SET_DECIMALS_FOR_LP = "SET_DECIMALS_FOR_LP";
export const SET_DECIMALS_FOR_ALIA = "SET_DECIMALS_FOR_ALIA";

export const DELETE_APPROVAL_FOR_LP = "DELETE_APPROVAL_FOR_LP";
export const DELETE_APPROVAL_FOR_ALIA = "DELETE_APPROVAL_FOR_ALIA";
export const DELETE_DECIMALS_FOR_LP = "DELETE_DECIMALS_FOR_LP";
export const DELETE_DECIMALS_FOR_ALIA = "DELETE_DECIMALS_FOR_ALIA";

export const SET_VALUES_FOR_ALIA_PRICE = "SET_VALUES_FOR_ALIA_PRICE";
export const SET_CIR_SUPP_FOR_LP = "SET_CIR_SUPP_FOR_LP";

export const SET_TOTAL_FARMS = "SET_TOTAL_FARMS";
export const SET_TOTAL_STAKES = "SET_TOTAL_STAKES";

export const SET_TRANSACTION_IN_PROGRESS = "SET_TRANSACTION_IN_PROGRESS";

export const SET_LANGUAGE = "SET_LANGUAGE";

export const SET_APY_ALIA = "SET_APY_ALIA";
export const SET_APY_LP = "SET_APY_LP";

export const SET_ALL_TOKENS = "SET_ALL_TOKENS";
export const SET_3D_ASSETS = "SET_3D_ASSETS";
export const SET_2D_ASSETS = "SET_2D_ASSETS";
export const SET_SINGLE_NFT = "SET_SINGLE_NFT";
export const SET_ALL_NFTS = "SET_ALL_NFTS";
export const REMOVE_ALL_NFTS = "REMOVE_ALL_NFTS";

export const GET_NFT_LIST = "GET_NFT_LIST";